[bastion]
51.250.82.97

[webservers]
10.0.1.10
10.0.2.20

[prometheus]
10.0.1.18

[grafana]
10.0.3.34

[elasticsearch]
10.0.1.7

[kibana]
10.0.3.11

[servers:children]
webservers
prometheus
grafana
elasticsearch
kibana