---
- name: Установка и настройка Nginx
  hosts: webservers
  become: yes

  tasks:

  - name: Установка Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Запуск Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Создание главной страницы сайта
    copy:
      dest: /var/www/html/index.html
      content: |
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Курсовой проект</title>
        </head>
        <body>
            <h1>Курсовой проект</h1>
            <p>Борисенко Даниил</p>
        </body>
        </html>